### PR TITLE
Fix cyclic import edge exclusion with `--jobs`

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description
Follow-up to bf8051b632afdba6792e55c20faec712b0ebebaf. I need to also combine the data collected during the multiprocessing about excluded edges. I wondered about this during development but unfortunately didn't fully test it.

(Sorry for all the PR volume! It won't be like this forever. No rush on the reviews.)

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM !

> Sorry for all the PR volume! It won't be like this forever. No rush on the reviews.

Ho no, I was hoping you'd fix all the major problems in pylint in 2 weeks, considering the frequency and importance of problems resolved, you were on track to do it 😄

**Comment by cdce8p** [comment]
I'm currently catching up on the latest changes. This one seems to break my custom CI runs for Home Assistant. Every time I include it, shortly before I expect pylint to finish, I get a `Error: The operation was canceled.` message.

Reverting just f815e9f does fix it though.

Example CI runs:
Good (768c02688eab70d40a449a590cfff885bef2131e): https://github.com/cdce8p/ha-core/actions/runs/5496467930/jobs/10016508120#step:17:32
Bad (f815e9f): https://github.com/cdce8p/ha-core/actions/runs/5496471817/jobs/10016514653#step:17:33

**Comment by jacobtylerwalls** [comment]
I'll take a look. Does disabling cyclic-import also resolve the issue?

**Comment by jacobtylerwalls** [comment]
> Every time I include it, shortly before I expect pylint to finish, I get a Error: The operation was canceled. message.

What I'm worried about is that the memory cost of the cyclic import checker algorithm is the problem, rather than this PR, and that it's been swept under the rug this whole time because the whole check never even ran with `--jobs` before. If that's the case, how do you think we should proceed?

**Comment by cdce8p** [comment]
> Does disabling cyclic-import also resolve the issue?

It was already disabled, so unfortunately no.

> > Every time I include it, shortly before I expect pylint to finish, I get a Error: The operation was canceled. message.
> 
> What I'm worried about is that the memory cost of the cyclic import checker algorithm is the problem, rather than this PR

I've never before gotten the message `The operation was canceled` without any indication to what actually caused it, so it could be a memory issue. However, I also just ran a test with `jobs=1` which worked fine.

That leads me to believe it's actually the step that combines the results which might be the problem.

**Comment by jacobtylerwalls** [comment]
> It was already disabled, so unfortunately no.

That sounds like an easy problem to address. Opened #8838 for it.

**Pull request merged**
