### PR TITLE
Merge maintenance 2.17.x in main following 2.17.2 release

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**

### CODE REVIEW

**Review by DanielNoord — COMMENTED** [review]
Shouldn't this also remove some news fragments?

**Comment by Pierre-Sassoulas** [comment]
We're voluntarily keeping them for the next minor release.

**Comment by DanielNoord** [comment]
So the entry shows up in `2.18.0` and `2.17.2`?

**Comment by Pierre-Sassoulas** [comment]
Yeah I had the same question than you for 2.16 actually but I don't remember exactly where it was discussed. (The fact that it make merge easier is convenient).

**Comment by DanielNoord** [comment]
Hmm this does feel weird, but okay I guess?

**Review by DanielNoord — APPROVED** [review]

**Pull request merged**
