### PR TITLE
Update astroid version to 3.1.0

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
https://github.com/pylint-dev/astroid/releases/tag/v3.1.0

### CODE REVIEW

**Comment by cdce8p** [comment]
@jacobtylerwalls Would you mind taking a look at the remaining issues? One for `used-before-assignment` is related to https://github.com/pylint-dev/astroid/pull/2345, the other `invalid-name` (3.12 only) likely to https://github.com/pylint-dev/astroid/pull/2330.

**Comment by jacobtylerwalls** [comment]
Sure thing. I already have a PR with the invalid_name update, let me retarget this branch and see if that does it.

**Comment by jacobtylerwalls** [comment]
@cdce8p ah, I can't because your upgrade branch is on your fork. I'll find time to test locally later.

**Comment by jacobtylerwalls** [comment]
I would suggest not backporting, as it will introduce new messages most likely.

**Comment by jacobtylerwalls** [comment]
Let's just do pylint 3.1 this weekend.

**Comment by cdce8p** [comment]
Thanks @jacobtylerwalls 🚀 Release `3.1.0` instead sounds good to me. The changes here look fine, I just can't approve my own PR.

**Review by jacobtylerwalls — APPROVED** [review]
Thanks!

**Comment by Pierre-Sassoulas** [comment]
I'm going to release 3.0.4 now then.

**Pull request merged**
