### PR TITLE
Drop support for Python 3.7

### PR DESCRIPTION
**Pull request by cdce8p**
## Description
Python 3.7 will reach its EOL in two months (2023-06-27). I think it would make sense to drop support with the next release `3.0`. That will allow us to cleanup even more old code.

I'm **not** proposing to remove the ability to lint `3.7` compatible code. If users want that, they can still set `py-version=3.7`.

Refs #6306

### CODE REVIEW

**Comment by DanielNoord** [comment]
I would defer this choice to https://github.com/pylint-dev/astroid/pull/2137#issuecomment-1519106161, as I think this is where we will make the first/final decision about this.

**Comment by cdce8p** [comment]
> I would expect some change in the functional tests too (py 3.7 exclusive tests that now need a py-version to run).

This is just a first step. Besides the test cases, there are other areas which could be improved. Had to start somewhere.

> Assignment expressions

Yeah, we could start using them with `3.8`. Although I'm not sure we should enable the code-style check for it. Sometimes using `:=` is an opinionated decision which the check just can't do.

**Comment by Pierre-Sassoulas** [comment]
Regarding the functional tests we could have a regression if it never run in the CI, right ? (Added https://github.com/pylint-dev/pylint/issues/6306#issuecomment-1519118923 so we do not forget later)

**Comment by cdce8p** [comment]
> Regarding the functional tests we could have a regression if it never run in the CI, right ? (Added [#6306 (comment)](https://github.com/pylint-dev/pylint/issues/6306#issuecomment-1519118923) so we do not forget later)

`py-version` isn't a full replacement. For example for `bad-reversed-sequence` we check the argument `locals` to see if it contains the `__reversed__` protocol method. This will always be true when pylint is run with `>= 3.8` so it can't detect an issue for `3.7`. That's why I would usually recommend to run pylint with the lowest supported Python version.

However, as this is the only small regression I still think dropping 3.7 now is worth it. If someone really depended on it, he can continue to use pylint `2.17.x`.

**Review by Pierre-Sassoulas — COMMENTED** [review]
I think the primer fail is expected in this PR. I'm a little worried that all MR will need to be rebased on main after we merge but I don't think we have a way to avoid that.

**Comment by cdce8p** [comment]
> I think the primer fail is expected in this PR. I'm a little worried that all MR will need to be rebased on main after we merge but I don't think we have a way to avoid that.

Yeah, that's just the nature of these cleanups.
However, I would rebase on a need bases only, not proactive. It's likely some of the breaking changes in astroid will cause additional merge conflicts down the line.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
