### PR TITLE
Bump astroid to 3.3.4

### LINKED ISSUE #9947: Pylint 3.3.0 does not recognize f-string as string and reports no-member for startswith()
### Bug description

The following file test_pylint.py:

```python
#!/usr/bin/env python
"""module"""


class Cls:
    # pylint: disable=too-few-public-methods
    """Cls"""


c_obj = Cls()

c_repr1 = '{!r}'.format(c_obj)  # pylint: disable=consider-using-f-string
c_repr2 = f'{c_obj!r}'

assert c_repr1.startswith('<__main__.Cls')
assert c_repr2.startswith('<__main__.Cls')  # pylint reports no-member
```

causes pylint to report this issue:

```
$ pylint test_pylint.py 
************* Module tmp_issues.test_pylint
test_pylint.py:16:7: E1101: Instance of 'Cls' has no 'startswith' member (no-member)
```

I tested this with multiple pylint versions, and the first version that has this behavior is pylint 3.3.0.

### Command used

```shell
pylint test_pylint.py
```

### Pylint output

```python
************* Module test_pylint
test_pylint.py:16:7: E1101: Instance of 'Cls' has no 'startswith' member (no-member)
```

### Expected behavior

Pylint should not report this as an error, because an f-string is a string and has the startswith() method.

### Pylint version

```shell
pylint    3.3.0
astroid   3.3.3
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
```

### OS / Environment

macOS Sonoma 14.6.1

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
Closes #9947

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by akamat10** [comment]
Ignoring the sentry `import-error` errors, which are expected, it seems like there might a couple more caching related bugs lurking in there. Will check.

**Comment by akamat10** [comment]
Looks like the common pattern is that the errors are f-string related. Perhaps a regression related to the JoinStr changes that happened in astroid https://github.com/pylint-dev/astroid/commit/3dbf1393de191fd10b09741badfe1b075fdadbac

**Comment by akamat10** [comment]
Sorry may be the attempted fix for JoinStr in 3.3.4 version is causing other issues.

**Comment by jacobtylerwalls** [comment]
I think the 3.3.4 JoinedStr fix is causing desired changes in the primer baseline, see #9963.

**Comment by akamat10** [comment]
You are right. Almost all of these are the result of the f-string inference working correctly.  One message is a head scratcher. The following looks like a new false postive, doesn't it?

> not-callable:
> visitf is not callable
> https://github.com/psf/black/blob/8d9d18c0338d9fbfc27b38f6f69bb630d90512fa/src/black/nodes.py#L172

On a positive note, I don't think I think there are any known primer issues anymore!!

**Comment by jacobtylerwalls** [comment]
> The following looks like a new false postive, doesn't it?

Well, `not-callable` apparently wants every inferred value, including None, to be callable...

https://github.com/pylint-dev/pylint/blob/8630cfd34a211b0d8135dbd79244a1fab4780b1d/pylint/checkers/typecheck.py#L1370-L1372

... but here we can rule out None because we're under an implicit boolean check. If the check were `is not None` I think it would be fixed by the astroid inference constraint for is None. We need more astroid inference constraints implemented. I've labeled a grand total of one pylint issue so far with "needs astroid constraint" but this would be one of them (there will be many more.)
***
> On a positive note, I don't think there are any known primer issues anymore!!

Thank you, this was a huge contribution on your part! No more apologies to contributors for distracting primer feedback! And of course fewer end-user headaches!

**Comment by Pierre-Sassoulas** [comment]
Yeah, thank you for your work on primers @akamat10 !

**Comment by akamat10** [comment]
Sounds good. Thanks for the explanation @jacobtylerwalls

**Pull request merged**
