### PR TITLE
Fix linterstats.get_module_message_count()

### LINKED ISSUE #9145: 'warnings by module' table missing in a report
### Bug description

```python
Table 'warnings by module' missing in a report
```

### Configuration

_No response_

### Command used

```shell
echo foo > module1.py
echo bar > module1.py
pylint -ry module1.py module2.py
```

### Pylint output

```python
************* Module module1
module1.py:1:0: C0114: Missing module docstring (missing-module-docstring)
module1.py:1:0: W0104: Statement seems to have no effect (pointless-statement)
module1.py:1:0: E0602: Undefined variable 'foo' (undefined-variable)
************* Module module2
module2.py:1:0: C0114: Missing module docstring (missing-module-docstring)
module2.py:1:0: W0104: Statement seems to have no effect (pointless-statement)
module2.py:1:0: E0602: Undefined variable 'bar' (undefined-variable)


Report
======
2 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |2      |NC         |NC         |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|method   |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|function |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+



6 lines have been analyzed

Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |4      |66.67 |NC       |NC         |
+----------+-------+------+---------+-----------+
|docstring |0      |0.00  |NC       |NC         |
+----------+-------+------+---------+-----------+
|comment   |0      |0.00  |NC       |NC         |
+----------+-------+------+---------+-----------+
|empty     |2      |33.33 |NC       |NC         |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |NC       |NC         |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |NC       |NC         |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |2      |NC       |NC         |
+-----------+-------+---------+-----------+
|refactor   |0      |NC       |NC         |
+-----------+-------+---------+-----------+
|warning    |2      |NC       |NC         |
+-----------+-------+---------+-----------+
|error      |2      |NC       |NC         |
+-----------+-------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|undefined-variable       |2           |
+-------------------------+------------+
|pointless-statement      |2           |
+-------------------------+------------+
|missing-module-docstring |2           |
+-------------------------+------------+




-----------------------------------
Your code has been rated at 0.00/10
```

### Expected behavior
```
************* Module module1
module1.py:1:0: C0114: Missing module docstring (missing-module-docstring)
module1.py:1:0: W0104: Statement seems to have no effect (pointless-statement)
module1.py:1:0: E0602: Undefined variable 'foo' (undefined-variable)
************* Module module2
module2.py:1:0: C0114: Missing module docstring (missing-module-docstring)
module2.py:1:0: W0104: Statement seems to have no effect (pointless-statement)
module2.py:1:0: E0602: Undefined variable 'bar' (undefined-variable)


Report
======
2 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |2      |2          |=          |0.00        |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|method   |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+
|function |0      |NC         |NC         |0           |0        |
+---------+-------+-----------+-----------+------------+---------+



6 lines have been analyzed

Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |4      |66.67 |4        |=          |
+----------+-------+------+---------+-----------+
|docstring |0      |0.00  |NC       |NC         |
+----------+-------+------+---------+-----------+
|comment   |0      |0.00  |NC       |NC         |
+----------+-------+------+---------+-----------+
|empty     |2      |33.33 |2        |=          |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |0        |0          |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |0.000    |=          |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |2      |2        |2          |
+-----------+-------+---------+-----------+
|refactor   |0      |0        |0          |
+-----------+-------+---------+-----------+
|warning    |2      |2        |2          |
+-----------+-------+---------+-----------+
|error      |2      |2        |2          |
+-----------+-------+---------+-----------+



% errors / warnings by module
-----------------------------

+--------+------+--------+---------+-----------+
|module  |error |warning |refactor |convention |
+========+======+========+=========+===========+
|module2 |50.00 |50.00   |0.00     |50.00      |
+--------+------+--------+---------+-----------+
|module1 |50.00 |50.00   |0.00     |50.00      |
+--------+------+--------+---------+-----------+



Messages
--------

+-------------------------+------------+
|message id               |occurrences |
+=========================+============+
|undefined-variable       |2           |
+-------------------------+------------+
|pointless-statement      |2           |
+-------------------------+------------+
|missing-module-docstring |2           |
+-------------------------+------------+




------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Pylint version

```shell
pylint 2.15.5
astroid 2.12.12
Python 3.10.8 (main, Nov 10 2022, 12:59:17) [GCC 11.2.1 20220219]
```

### OS / Environment

Alpine Linux v3.16.3 ([Dockerfile](https://github.com/cytopia/docker-pylint/blob/0.8/Dockerfiles/Dockerfile))

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by zasca**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #9145

### CODE REVIEW

**Review by DanielNoord — COMMENTED** [review]
Could you add a test for this behaviour? And perhaps also a news fragment using `towncrier`?

**Review by Pierre-Sassoulas — COMMENTED** [review]
@zasca do you think you might have time to add automated tests for this ? It would be great if it could go in 3.0.3 :)

**Review by jacobtylerwalls — APPROVED** [review]

**Review by Pierre-Sassoulas — APPROVED** [review]
```
nt/checkouts/9146/doc/user_guide/messages/warning/implicit-str-concat.rst:55: 
WARNING: Lexing literal_block '[STRING_CONSTANT]\ncheck-str-concat-over-line-jumps = yes' 
as "toml" resulted in an error at token: 'y'. Retrying in relaxed mode.
```
Feel like this need a rebase on main /merge from main to be fixed. Otherwise LGTM

**Comment by jacobtylerwalls** [comment]
Thanks for the contribution @zasca!

**Pull request merged**
