### PR TITLE
Harden primer package caching against possible race condition

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
Refs https://github.com/pylint-dev/pylint/pull/9925#issuecomment-2358249852

cc/ @akamat10

### CODE REVIEW

**Comment by akamat10** [comment]
Isn't there a clean way to fix it instead of using a heuristic?

**Comment by jacobtylerwalls** [comment]
Redesigning the parallelization of the primer sounds like the way to fix it cleanly, but if a fix doesn't develop over the next few days I guess I'd rather have this than nothing.

**Comment by jacobtylerwalls** [comment]
That said, this check might not be in the right place, looking into it.

**Comment by jacobtylerwalls** [comment]
I reread https://github.com/pylint-dev/pylint/pull/9925#issuecomment-2358249852 and paid closer attention to what you said about `continue-on-error: true`. I'll close this out and try another approach now that I understand your theory better!

**Pull request closed without merging**
