### PR TITLE
Add to missing timeout

### PR DESCRIPTION
**Pull request by joel6948**
Changed to missing-timeout folder as per req

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
You should modify the existing checker it's here https://github.com/pylint-dev/pylint/blob/10a093ea85f8cb2a3268f439c3b1f40319023956/pylint/checkers/method_args.py#L73

**Comment by Pierre-Sassoulas** [comment]
Also please let everything happen in the existing pull request #9526 it's better to not open new merge request :)

**Comment by joel6948** [comment]
> Also please let everything happen in the existing pull request #9526 it's better to not open new merge request :)

tahnk you for your advice man i am bit new in this open source

**Comment by joel6948** [comment]
> You should modify the existing checker it's here
> 
> https://github.com/pylint-dev/pylint/blob/10a093ea85f8cb2a3268f439c3b1f40319023956/pylint/checkers/method_args.py#L73

commited the changes

**Pull request closed without merging**
