### PR TITLE
Merge maintenance/3.2.x into main following 3.2.7 release 

### PR DESCRIPTION
**Pull request by jacobtylerwalls**

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
I can't find the additional commits here, which is the entire point?

**Comment by Pierre-Sassoulas** [comment]
What I did:
```bash
git switch post-3.2.7
git reset --hard origin/main
git merge origin/maintenance/3.2.x
# (resolve merge conflicts)
git merge --continue
git push --force
```

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
I wonder why we have regression tests added. Should we remove them ?

**Comment by jacobtylerwalls** [comment]
Yes, I had to move them on the backport to stay under the 50 file limit, let's not create dupes on main

**Comment by Pierre-Sassoulas** [comment]
Aye aye, came to the same conclusion, it's duplicated between reg and reg02.

**Comment by Pierre-Sassoulas** [comment]
(Same thing for the rc file for unreacheable, we don't need that on main as we dropped 3.8)

**Review by Pierre-Sassoulas — DISMISSED** [review]

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Sorry I force pushed and removed your changes.

**Review by Pierre-Sassoulas — APPROVED** [review]
nevermind :D

**Comment by jacobtylerwalls** [comment]
Thanks for the help!

**Pull request merged**
