### PR TITLE
[governance] Upgrade governance for pylint plugin maintainers

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

This is up for discussion: do we give pylint's maintenance right for plugin maintainers that want to migrate their plugin to pylint-dev ? Previously we invited Carl Crowder for pylint-django, when he wanted to migrate his plugin to pylint-dev but he was a PyCQA member, and already pretty invested in pylint so already had maintainer's rights. How about a master student that did their plugin in isolation and the plugin is not yet widely adopted ?

We can also create separate rights' groups in the org (admin / member / plugin owner).

### CODE REVIEW

**Review by DanielNoord — DISMISSED** [review]
I think a separate user group would be useful!

**Comment by PeterHamfelt** [comment]
Hey,
Thanks, Pierre, for creating the PR and taking the time to discuss it. :)
In my master's thesis, I focused on building a standalone static code analysis tool that uses Astroid and a simplified visitor pattern to identify ML-specific code smells. Based on this, I believe a pylint-ml extension would be a valuable contribution to the Python ML community. It would facilitate further research and development while also standardizing practices in the field.
Similarly, adopting a documentation setup like Pylint's would streamline the process and make it easier for others to contribute.
/Peter

**Comment by Pierre-Sassoulas** [comment]
> I think a separate user group would be useful!

So with maintainer and/or triager rights on pylint ? Or only admin rights on their plugin repository ? The current version of the doc means maintainers rights on pylint and admin rights on their plugin. I think it makes sense, creating a plugin (depending on the plugin of course) is equivalent effort as doing 2 major contributions and it's certainly "taking ownership of a part of the code".

**Review by jacobtylerwalls — DISMISSED** [review]

**Comment by DanielNoord** [comment]
> > I think a separate user group would be useful!
> 
> So with maintainer and/or triager rights on pylint ? Or only admin rights on their plugin repository ? The current version of the doc means maintainers rights on pylint and admin rights on their plugin. I think it makes sense, creating a plugin (depending on the plugin of course) is equivalent effort as doing 2 major contributions and it's certainly "taking ownership of a part of the code".

I think triager on `pylint` is fine for now? That way you can get to know a person as well.

**Review by jacobtylerwalls — APPROVED** [review]

**Pull request merged**
