### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by UlrichEckhardt**
This PR contains a bunch of tweaks to code, mostly dead code removal. Each commit should make sense on its own.

Questions:
* Should I split this into separate PRs?
* Should I file an issue for this PR?
* Should I create a changelog entry?

Generally, I'd be happy about feedback, since this is my first real contribution here.

Cheers! :)

Uli

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Hey @UlrichEckhardt , thank you for working on pylint. Refactoring is hard, you need to know the code well or at least have a need for refactor because you can't do a feature or fix a bug without the refactor (discussed with a maintainer first). In this case some refactoring are not equivalent (i.e. the else in the for loop), or are touching to an API that need to stay and not actually dead code (i.e. options in base checker). If you want to start contributing I suggest working on an issues labelled "good first issue" first. (doc on contributing here: https://pylint.readthedocs.io/en/stable/development_guide/contributor_guide/contribute.html).

**Comment by UlrichEckhardt** [comment]
Thanks for being my mentor here, @Pierre-Sassoulas. Just FYI, I'm working on baseline support, which I want for a project. That refactoring isn't crucial for that, I think. It's just some oddities I stumbled over trying to get familiar with the code base.

Concerning the objection to the else-after-for change, can you elaborate? Actually, I just found out that it fixes a warning raised by pylint itself, which was silenced in the adjacent line. Can you give me an example where the changed code behaves differently?

Concerning the `options` in base checker being an API, which would be broken, is there any way I could have known that, just to avoid it in the future? I was just looking at its use and found that it overrides the field defined in the `_ArgumentsProvider` base class withoud any change. My thought was that someone just forgot to move it while refactoring.

**Comment by Pierre-Sassoulas** [comment]
For example in https://github.com/pylint-dev/pylint/pull/9583/commits/07c71c1f582f2946900039252d3fcce97154c123, if the condition is never true, but the token has some elements to iterate on then it's not equivalent (you're not entering the else and ``quote_char`` is now undefined) . On closer inspection the string is always going to have at least two quote chars, but checking that requires time to review, and introduce a risk of mistake that we then would need to fix, maybe with a hotfix and a backport. It's not clear cut that the new code is better. Maintainer time could be used on something else more effectively (one of the 900 open issues 😄).

**Comment by UlrichEckhardt** [comment]
Sorry, but I'm still not understanding what you mean, apart from the 900+ open issues. My main point is that if you leave a loop via `break`, the `else` branch is not called. Only if you leave the loop regularly, the `else` branch is called. The loop variables (`_index`, `char`) are set/updated on every loop iteration, so they remain unset when the sequence is empty. In that case, the `else` branch is also automatically triggered, because it's a regular loop termination:

```python
def demo(seq: str):
    print(f'demo({seq!r})')
    for i, e in enumerate(seq):
        if e in "'\"":
            print('conditional branch in loop')
            try:
                print(f'i={i} e={e}')
            except UnboundLocalError:
                print('i/e are not set')
            break
    else:
        print('else branch after loop')
        try:
            print(f'i={i} e={e}')
        except UnboundLocalError:
            print('i/e are not set')
        return

    print('after loop')
    try:
        print(f'i={i} e={e}')
    except UnboundLocalError:
        print('i/e are not set')

if __name__ == '__main__':
    for s in ['', 'abc', '"abc"', "'abc'", "r'abc'", 'f"abc"']:
        demo(s)
        print('')
```

Actually, with that in mind, the code can be simplified even further, because there's no need for distinct `char` and `quote_char` variables:
```python
        for _index, quote_char in enumerate(token):
            if quote_char in "'\"":
                break
        else:
            return
```

I hope I don't across as a dick, I'm trying to not be one! Hopefully I'll also be able to compensate you for your time by working on the open issues, once I get more familiar with the code base.

**Comment by Pierre-Sassoulas** [comment]
Sorry, I might have misunderstood the code and it might be perfectly fine and equivalent to the previous one (not using for / else a lot). I'm not interested in reviewing refactors that were not discussed and deemed necessary beforehand.

**Pull request closed without merging**
