### PR TITLE
Add documentation for ``cyclic-import``

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Work in progress for cyclic-import documentation. Right now it's not triggered. Refs #7897

### CODE REVIEW

**Comment by ollie-iterators** [comment]
I decided to check out your documentation for cyclic import. I was able to fix some things by adding import sys and then sys.path.append('...'), but I keep getting an error saying that:

"/messages/c/cyclic-import/bad/worse.py:2: in <module>
    from  bad import count_to_one
doc/data/messages/c/cyclic-import/bad/bad.py:2: in <module>
    from worse import count_to_two  # [cyclic-import]
E   ImportError: cannot import name 'count_to_two' from partially initialized module 'worse' (most likely due to a circular import)"

**Comment by Pierre-Sassoulas** [comment]
Ha right, cyclic-import is a python error we need to  import inside the function in Bad.py. thank you for investigating

**Comment by ollie-iterators** [comment]
You're welcome

**Comment by ollie-iterators** [comment]
It also means you can document relative-beyond-top-level, which is also not documented.

**Comment by Pierre-Sassoulas** [comment]
Seem like it work when using the parent directory. The recursive option does not help.

```
$ pylint /home/pierre/pylint/doc/data/messages/c/cyclic-import/bad --disable=all --enable=F,cyclic-import,astroid-error,syntax-error  
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 0.00/10, +10.00)

$  pylint /home/pierre/pylint/doc/data/messages/c/cyclic-import --disable=all --enable=F,cyclic-import,astroid-error,syntax-error 

************* Module bad.bad
doc/data/messages/c/cyclic-import/bad/bad.py:1:0: R0401: Cyclic import (bad.bad -> bad.bad2) (cyclic-import)
------------------------------------------------------------------
Your code has been rated at 9.29/10 (previous run: 8.57/10, +0.71)
```

**Comment by jacobtylerwalls** [comment]
Resolved this with an `__init__.py` to make `/bad` a package. Similar to #8772.

**Review by jacobtylerwalls — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Thank you so much @jacobtylerwalls !

**Pull request merged**
