### PR TITLE
Add regression tests.

### PR DESCRIPTION
**Pull request by mbyrnepr2**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
|    | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |
| ✓   | 🧪 Tests          |

## Description

Refs #9069
Refs pylint-dev/astroid#2305

### CODE REVIEW

**Comment by mbyrnepr2** [comment]
Failing CI tests should be fixed when https://github.com/pylint-dev/astroid/pull/2307 is live.

**Comment by Pierre-Sassoulas** [comment]
Willte require astroid 2.15.8 when backporting, this is going to be easier to do manually.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Primer is non trivial to review, need to understand if it's change in the primed repo or due to astroid upgrade.

**Comment by jacobtylerwalls** [comment]
> Primer is non trivial to review, need to understand if it's change in the primed repo or due to astroid upgrade.

Mixture of astroid upgrade and 🤷‍♂️. The homeassistant/music21/pandas changes are same as in #9065. The others aren't. I have faith that we're making things less flaky overall, but I wouldn't say we've defeated flakiness (pylint-dev/astroid#2273 is outstanding).

**Comment by jacobtylerwalls** [comment]
> or due to astroid upgrade.

Oh, did you mean just this branch's upgrade from 3.0 beta to 3.0 final? I don't think there was anything substantive there for these primer results. If you search the closed PRs for some of the variable names mentioned in these primer messages like "ksIter" from music21 you'll see that they're `frequent flyers` ✈️ .

**Review by Pierre-Sassoulas — COMMENTED** [review]
Thank you for the insight @jacobtylerwalls. I think the fix to https://github.com/pylint-dev/pylint/issues/8998 will help us to make this review easier in the future by separating bleeding edge and upgrade.

I'm worried about pandas in particular (lots of new ``no-members`` FP). They do not seems to be due to changes on the bleeding edge repo we use (https://github.com/pandas-dev/pandas/blame/61d2056e4251b8d1c387f2577f0407062b9ab903/pandas/core/resample.py#L387 was modified 7 months ago and just appeared). I don't see anything obvious that we changed between the last alpha of astroid and now that could be the cause though.

**Comment by jacobtylerwalls** [comment]
> I don't see anything obvious that we changed between the last alpha of astroid and now that could be the cause though.

Actually this _is_ due to the change from 3.0b to 3.0 final. You can reproduce with:

```py
python3.11 -m pylint tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py --disable=all --enable=no-member
```

Before pylint-dev/astroid@89dfb485:
```
************* Module pandas.core.resample
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:387:15: E1101: Method '_selected_obj' has no 'groupby' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1484:18: E1101: Method '_obj_with_exclusions' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1520:15: E1101: Method '_selected_obj' has no 'ndim' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1521:23: E1101: Method '_selected_obj' has no 'name' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1531:15: E1101: Method '_selected_obj' has no 'ndim' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1533:64: E1101: Method '_selected_obj' has no 'name' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1641:16: E1101: Instance of '_GroupByMixin' has no '_resampler_cls' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1649:15: E1101: Instance of '_GroupByMixin' has no '_wrap_result' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1728:18: E1101: Method '_obj_with_exclusions' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1802:21: E1101: Method '_selected_obj' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1807:21: E1101: Method '_selected_obj' has no 'reindex' member (no-member)

------------------------------------------------------------------
Your code has been rated at 9.24/10 (previous run: 9.45/10, -0.21)
```

Then pylint-dev/astroid@89dfb485 (astroid 3.0 beta) removes 3 messages:
```
************* Module pandas.core.resample
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1484:18: E1101: Method '_obj_with_exclusions' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1521:23: E1101: Method '_selected_obj' has no 'name' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1533:64: E1101: Method '_selected_obj' has no 'name' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1641:16: E1101: Instance of '_GroupByMixin' has no '_resampler_cls' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1649:15: E1101: Instance of '_GroupByMixin' has no '_wrap_result' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1728:18: E1101: Method '_obj_with_exclusions' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1802:21: E1101: Method '_selected_obj' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1807:21: E1101: Method '_selected_obj' has no 'reindex' member (no-member)

------------------------------------------------------------------
Your code has been rated at 9.45/10 (previous run: 9.24/10, +0.21)
```

Then astroid 3.0 final reverts, giving the original 11 messages again:
```
************* Module pandas.core.resample
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:387:15: E1101: Method '_selected_obj' has no 'groupby' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1484:18: E1101: Method '_obj_with_exclusions' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1520:15: E1101: Method '_selected_obj' has no 'ndim' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1521:23: E1101: Method '_selected_obj' has no 'name' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1531:15: E1101: Method '_selected_obj' has no 'ndim' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1533:64: E1101: Method '_selected_obj' has no 'name' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1641:16: E1101: Instance of '_GroupByMixin' has no '_resampler_cls' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1649:15: E1101: Instance of '_GroupByMixin' has no '_wrap_result' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1728:18: E1101: Method '_obj_with_exclusions' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1802:21: E1101: Method '_selected_obj' has no 'copy' member (no-member)
tests/.pylint_primer_tests/pandas-dev/pandas/pandas/core/resample.py:1807:21: E1101: Method '_selected_obj' has no 'reindex' member (no-member)
```
***
The reason the messages went away in pylint-dev/astroid@89dfb485 is because inference got worse, and no-member gets shy when things are uninferable:

3.0 beta:
```py
(Pdb) node.expr
<Attribute._selected_obj l.1520 at 0x106b61d90>
(Pdb) node.expr.inferred()
[Uninferable]
```
versus 3.0 final
```py
(Pdb) node.expr
<Attribute._selected_obj l.1520 at 0x107619e10>
(Pdb) node.expr.inferred()
[<BoundMethod _selected_obj of pandas.core.groupby.groupby.BaseGroupBy at 0x4817398224]
```
***
So I think we're good here.

**Comment by jacobtylerwalls** [comment]
I guess going forward we should be careful about backporting things that involve inference changes.

**Comment by Pierre-Sassoulas** [comment]
It also seems ``no-member`` is not favoring false negatives when the inference fail. I don't think this is what we usually do. Not sure if it can be inverted at this point, primer would need to be very carefully checked if we do that (could be a strong point of pylint for users ?).

**Pull request merged**
