### PR TITLE
Support `cyclic-import` message with `--jobs`

### LINKED ISSUE #4171: No cyclic-import messages with jobs=0
Running `pylint -jobs=0` does not report about cyclic-import. This can be reproduced with a trivial example.
`a.py`:
```
import b
```
`b.py`:
```
import a
```

This issue is not new to pylint 2.7. It is more noticeable only because running jobs in parallel became more useful in this version.
```
pylint --version
pylint 2.7.1
astroid 2.5
Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0]
```

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes
|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description
Closes #4171

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
LGTM, but I don't understand why we cover the reduce without covering the get_map_data.. Should we `pragma: no cover` it ?

**Comment by jacobtylerwalls** [comment]
I verified that the line is being hit, but it's hit during parallel processing, so there could be a bug in codecov. Let's not add a pragma for something that's a bug in codecov.

**Review by DanielNoord — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
The [skip ci] in the terminal commit prevent the CI from running properly.

**Comment by jacobtylerwalls** [comment]
> The [skip ci] in the terminal commit prevent the CI from running properly.

I did it on purpose to avoid wasting resources on linting a commit that removed lines from an RST file. I'll just override :-)

**Comment by jacobtylerwalls** [comment]
Also, GitHub was not showing additional commits this morning, I opened a bug report with them and they just said "it happens sometimes" and didn't show it on githubstatus or anything.

**Comment by jacobtylerwalls** [comment]
Also, the primer was failing on the first commit because the project cache was missing. It's possible that without frequent enough commits on main, the PRs will always fail because the needed cache gets evicted?

**Comment by Pierre-Sassoulas** [comment]
I was wondering about the primer too. Funny that we would have an unusual drop in commit frequency and hitting never seen bugs :smile: (I blame the high temperatures, and the attention astroid is getting lately).

**Pull request merged**
