### PR TITLE
[return-arg-in-generator] Add a details.rst only as the message is not raised anymore

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description

Blocked by the inclusion of deleted messages in the doc (#6670) or the inclusion of a new message template #7897 

Refs #5953

### CODE REVIEW

**Comment by ollie-iterators** [comment]
If you are doing things that only need details.rst, I believe that the invalid-unicode-codec one only needs deatils.rst because it is about the encoding of the file.

**Comment by Pierre-Sassoulas** [comment]
See https://pylint--8191.org.readthedocs.build/en/8191/user_guide/messages/error/return-arg-in-generator.html

**Comment by mbyrnepr2** [comment]
Savvy! Although could probably do with removing the word “outside” from the description (not part of the current MR).

**Comment by Pierre-Sassoulas** [comment]
Nice catch, I fixed it :)

**Review by mbyrnepr2 — APPROVED** [review]

**Pull request merged**
