### PR TITLE
Add tests for existing Pyreverse bugs

### PR DESCRIPTION
**Pull request by nickdrozd**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description

Add tests for existing bugs:

- https://github.com/pylint-dev/pylint/issues/8189
- https://github.com/pylint-dev/pylint/issues/8522
- https://github.com/pylint-dev/pylint/issues/8888

Running the last of these tests successfully requires adding a `sort` call, which is an extremely minor change in behavior.

### CODE REVIEW

**Review by Pierre-Sassoulas — DISMISSED** [review]
LGTM

**Comment by nickdrozd** [comment]
BTW, I have fixes for all of these. The logical error is the same, but implemented in three different ways. Should they go up in one PR or in three separate PRs?

**Comment by Pierre-Sassoulas** [comment]
Ha I thought you just wanted to add the tests. Well if you have the fixes how about creating 3 PRs and fixing at the same time as adding the relevant tests? Feels clearer if we need to check the git history / PR later imo.

**Comment by nickdrozd** [comment]
The behaviors and changes involved are subtly different, so I think separating everything will help to make clear exactly what is affected by what. So if the tests for the buggy behavior are set up first, then the commits with the changes will show the changes to that behavior.

**Comment by nickdrozd** [comment]
Added a test for https://github.com/pylint-dev/pylint/issues/8671

**Review by Pierre-Sassoulas — APPROVED** [review]

**Review by DudeNr33 — APPROVED** [review]
Sounds like a good plan to better understand the following PRs and changes in behaviour.

One heads up for the added `sorted` call:
https://github.com/pylint-dev/pylint/issues/8776 
We discussed if this is a wanted behavior or not, and ended with saying it would probably be best to add a command line switch to enable/disable sorting. 
But that's a different topic, and as we already sort other stuff I'm totally fine with adding the `sorted` call here as well.

**Pull request merged**
