### PR TITLE
Fix suggestion for min-max with expressions

### LINKED ISSUE #8524: `nested-min-max` (W3301) is still giving a wrong suggestion in some cases
### Bug description

With the following code
```python
""" An example where pylint gives a wrong suggestion """
max(3, max([5] + [i for i in range(6,10) if i % 2 == 0]))
```
pylint detects a nested call of `max` and suggests to just remove the inner `max`.  But this leads to a type error:
```
TypeError: '>' not supported between instances of 'list' and 'int'
```

### Configuration

_No response_

### Command used

```shell
pylint a.py
```

### Pylint output

```shell
************* Module a
a.py:2:0: W3301: Do not use nested call of 'max'; it's possible to do 'max(3, [5] + [i for i in range(6, 10) if i % 2 == 0])' instead (nested-min-max)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

### Expected behavior

At the very least not give a wrong suggestion, but ideally give a right one, like for other instances of this problem recently addressed in https://github.com/pylint-dev/pylint/issues/8168 and https://github.com/pylint-dev/pylint/pull/8234.

For instance, with
```python
max(3, max([5] + [4]))
```
we now get the working suggestion to replace it with
```python
max(3, *[5] + [4])
```
so we could suggest in this case too to add a `*`:
```python
max(3, *[5] + [i for i in range(6, 10) if i % 2 == 0])
```
(In this case, one could of course even be smarter, but this may be too specific.)

### Pylint version

```shell
pylint 2.17.0
astroid 2.15.0
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
```

### OS / Environment

_No response_

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by theirix**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Fixes suggestion when list or dict comprehensions are used or combined with add/or operators.

Closes #8524

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Hmm, I think the primer failed because the interpreter changed when we added python 3.12 in #9092 , would you mind rebasing, please ?

**Review by Pierre-Sassoulas — APPROVED** [review]
Code looks pretty good, that's a very nice first contribution 👍 Directly into 3.0.2 😄

**Comment by theirix** [comment]
> Code looks pretty good, that's a very nice first contribution 👍 Directly into 3.0.2 😄

Thank you!

> Hmm, I think the primer failed because the interpreter changed when we added python 3.12 in #9092 , would you mind rebasing, please ?

Rebased the branch. The only failing check is readthedocs. Please tell me if another rebase is needed when the fix is provided.

**Comment by Pierre-Sassoulas** [comment]
Outch, I broke the main branch, fixed by #9140, you can rebase 😅

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
