### PR TITLE
Also check Lambda for await-outside-async

### PR DESCRIPTION
**Pull request by UTsweetyfish**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Also check Lambda for await-outside-async.

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Looks straightforward, thank you. Could you simply add a fragment for a false negative ? As there's no related issue you can ref this MR directly in the fragment with ``Refs #9653``.

**Comment by UTsweetyfish** [comment]
> Looks straightforward, thank you. Could you simply add a fragment for a false negative ? As there's no related issue you can ref this MR directly in the fragment with `Refs #9653`.

Can you add that for me? I don't have `towncrier` installed. Thanks!

**Comment by Pierre-Sassoulas** [comment]
You can copy paste a file in https://github.com/pylint-dev/pylint/tree/main/doc/whatsnew/fragments and name it ``9653.false_negative`` :)

**Review by Pierre-Sassoulas — APPROVED** [review]
Great first contribution thank you !

**Pull request merged**
