### PR TITLE
Fix Pyreverse optional annotation bug

### LINKED ISSUE #9014: Redundant Optional in Pyreverse
### Bug description

```python
class A:
    q: int | None = None
```

Pyreverse generates:

```mmd
classDiagram
  class A {
    q : Optional[int | None]
  }
```

`Optional[int | None]` is redundant.  It should just be `int | None`.

### Configuration

_No response_

### Command used

```shell
pyreverse -o mmd
```

### Pylint output

```shell
classDiagram
  class A {
    q : Optional[int | None]
  }
```

### Expected behavior

classDiagram
  class A {
    q : int | None
  }

### Pylint version

```shell
pylint 3.0.0a8-dev0
astroid 3.0.0a10-dev0
```

### OS / Environment

_No response_

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by nickdrozd**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

Closes #9014

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
The pre-commit issue seems genuine.

**Comment by nickdrozd** [comment]
The typing around that section is a little squirrelly (see https://github.com/pylint-dev/pylint/issues/8266). Should be fixed now.

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Review by DudeNr33 — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
