### PR TITLE
Add detailed documentation for Pyreverse command-line options

### LINKED ISSUE #9573: Undocumented `--colorized` option for pyreverse in 3.2.0-dev0 docs
### Bug description

```python
In latest docs (3.2.0-dev-0) at time of writing there was no documentation for the --colorized option:
https://pylint.readthedocs.io/en/latest/pyreverse.html

I raise this issue because we've had a PR opened to integrate the option in a down-stream tool:
[sphinx-pyreverse](https://github.com/alendit/sphinx-pyreverse)
```

### Configuration

_No response_

### Command used

```shell
open https://pylint.readthedocs.io/en/latest/pyreverse.html
```

### Pylint output

```python
n/a
```

### Expected behavior

That the feature be documented :)

### Pylint version

```shell
pylint 3.2.0-dev
```

### OS / Environment

n/a

### Additional dependencies

```python
n/a
```

### PR DESCRIPTION
**Pull request by Julfried**
## Type of Changes
|     | Type                   |
| --- | ---------------------- |
|     | :bug: Bug fix          |
|     | :sparkles: New feature |
|     | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

## Description
Add detailed documentation for all Pyreverse command-line options, organized into logical sections:
- Output Control (format, directory, project settings)
- Filtering and Scope (filter modes, class focus, ancestors)
- Display Options (module names, colorization)
- Project Configuration (ignore patterns, source roots)

Closes #9573

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Thank you for your work on this. I feel like it should be based on the output of argparse so it's up to date automatically when we modify pyreverse input but it should be stable enough. Waiting for the pyreverse's experts opinion :D

**Review by DanielNoord — CHANGES_REQUESTED** [review]
Could you add this documentation to the options like so:
https://github.com/pylint-dev/pylint/blob/3fca43aa15047ff62f775c27d0c3e85aaa935549/pylint/pyreverse/main.py#L244

It would be a waste to not save the effort you made to write these.

We can then look into rendering these help texts correctly. 

We probably need a `doc` extension very similar to:
https://github.com/pylint-dev/pylint/blob/3fca43aa15047ff62f775c27d0c3e85aaa935549/doc/exts/pylint_options.py

**Comment by Julfried** [comment]
Thanks for the feedback. I agree, that it feels right to automate this for the future and maintaining the documenation texts directly in the code is a lot better for consistency. I will add my docs to the options, like you mentioned. Regarding the automation part I will have to look into this, but it feels like a bigger change, so I am not sure if I find the time for this right now :D

**Comment by DudeNr33** [comment]
I really like the grouped output, it is also a great benefit for the help output on the command line. Thanks!
Fully agree that automatically generating it would be ideal for the future, but personally I would be fine to put this in a follow-up PR.

One minor thing I noticed when running it locally: The docstring of the `Run` class is included below every option group, e.g.:

```shell
Filtering and Scope:
  Base class providing common behaviour for pyreverse commands.

  --filter-mode <mode>, -f <mode>
```

From a first glance I would say that is a side-effect from `ArgumentsManager._register_options_provider` being tailored towards the use cases of Pylint checker classes . 

As the `Run` class is fairly short and the docstring very generic, I am in favor of simply removing it.

**Comment by Julfried** [comment]
Thanks for the feedback. I think turning the docstring into a regular python comment to preserve documentation would be a good idea.

**Comment by Julfried** [comment]
Awesome, thank you! Will look into it👍

**Comment by DanielNoord** [comment]
Since I also changed the API for `pyreverse`: @DudeNr33 mind giving this a look?

@Pierre-Sassoulas rest of the PR can probably be reviewed by you? Unless @Julfried wants to make many changes to the documentation I would probably review this and do any follow up to the documentation itself in a subsequent PR that is fixed on the documentation. This is already doing quite a bit 😅

**Review by Pierre-Sassoulas — COMMENTED** [review]
Wow this sphinx plugin and the generated result looks amazing. Right now it's hard to see the new page because the main page have now link to it. So I would just reorganize the pyreverse doc a little accommodate the newly created page. Probably a main page with a lot less text and two links, one to the new page, and one to a new subpage with most of the current main page's text. What do you think ?

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by DanielNoord** [comment]
@Julfried Let me know if there is anything you want to change in this PR. If not, I will merge this!

**Comment by DanielNoord** [comment]
Merged!

@Julfried Are you up for making those last improvements?

**Pull request merged**
