### PR TITLE
Bump CI jobs to 3.12

### PR DESCRIPTION
**Pull request by jacobtylerwalls**

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
I'm not sure we have to make the default python interpreter 3.12 yet, but we should test our code on the actual 3.12 not 3.12 dev

**Review by Pierre-Sassoulas — DISMISSED** [review]

**Comment by mbyrnepr2** [comment]
Error: The version '3.12' with architecture 'x64' was not found for Ubuntu 22.04.
[17](https://github.com/pylint-dev/pylint/actions/runs/6382826857/job/17322229986?pr=9092#step:3:18)
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

**Review by Pierre-Sassoulas — COMMENTED** [review]
Forgot to leave the review when I was on mobile.

**Comment by jacobtylerwalls** [comment]
(Primer will remain failing until we get a 3.12 run on main.)

**Comment by mbyrnepr2** [comment]
3.12 action is available now right? https://github.com/actions/python-versions

**Comment by mbyrnepr2** [comment]
Do we want to add 3.12 to the `tox.ini` while we're here?

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
