### PR TITLE
Fix source root not recognized

### LINKED ISSUE #10026: Source root not correctly used
### Bug description

I have a package that sits in a child folder of the current working directory (./src). Now if I want to to run pyreverse for this module I add ./src as a source-root. However pyreverse does not find the module.

Here is an example:

```cmd
ex/
└── src/
    ├── __init__.py
    └── mymodule/
        ├── __init__.py
        └── testmodule.py
```

### Configuration

_No response_

### Command used

pyreverse -o html --source-root ./src mymodule

### Pylint output

raise ImportError(f"No module named {'.'.join(module_parts)}")
ImportError: No module named mymodule

### Expected behavior

When specifiy source-roots, pyreverse should also search the modules in this path

### Pylint version

pylint 3.3.1
astroid 3.3.5
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 15:47:54) [MSC v.1941 64 bit (AMD64)]

### OS / Environment

win64

### Additional dependencies

_No response_

### PR DESCRIPTION
**Pull request by Julfried**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

Closes #10026

This PR fixes a bug in the `discover_package_path` function in pylint/pyreverse. The function was incorrectly handling cases where the source root is a child of the module directory, causing issues when using pyreverse with certain project structures, particularly those with a `src` layout.

The fix modifies the condition for identifying the correct source root, allowing it to handle both cases where the source root is a parent or a child of the module directory.

Changes made:
- Updated the condition in `discover_package_path` function to correctly identify the source root:
  ```python
  if os.path.commonpath([source_root, dirname]) in [dirname, source_root]:
      return source_root

### CODE REVIEW

**Comment by DanielNoord** [comment]
Thanks for the fix! Are you able to add a test for this as well?

**Comment by Julfried** [comment]
Thank you, I will take a look into it this week!

**Comment by DanielNoord** [comment]
Could you fix CI for the style and changeling checks? I think the PR itself looks really good already, thanks! 😄

**Comment by Julfried** [comment]
Thank you, typo should be fixed

**Review by Pierre-Sassoulas — COMMENTED** [review]
Hey @Julfried thank you for fixing the typo, do you mind adding a fragment for the changelog please ? 

Here: https://github.com/pylint-dev/pylint/tree/main/doc/whatsnew/fragments

(https://pylint.readthedocs.io/en/stable/development_guide/contributor_guide/contribute.html#creating-a-pull-request)

**Comment by Julfried** [comment]
Thank you. The fragment should be added!

**Review by DanielNoord — APPROVED** [review]
Thanks!

**Comment by echoix** [comment]
Hi!

I stumbled upon the same issue that this PR solves. Using a pylint version installed with a git url+hash through pip makes using source-roots work. Since it is not published yet, do you have any guidance on how source-roots should have been used originally? I can't find any usage pattern that would make it work at all according to the couple sentences present in the docs. I tried for hours now stepping through "/usr/local/python/3.12.7/lib/python3.12/site-packages/pylint/lint/expand_modules.py:discover_package_path()" with different combinations of invocations trying to have one that would match the one when using the developpement version (`pip install git+https://github.com/pylint-dev/pylint@9b272cca71d0e1733c0aa75dc05d293ec99d44c0`, uninstalling pylint before changing between released and git versions.)

If there's absolutely no workaround, can you consider backporting this specific fix to a version that would be released sooner?

**Comment by Pierre-Sassoulas** [comment]
Hi @echoix I've created #10083  to backport, waiting for the opinion of other maintainers before merging because this is a part that is hard to test and historically caused a lot of problem (maybe not well suited to a patch release). While waiting for the release you can use an install using git for example: ``pip install git+git://http://github.com/pylint-dev/pylint.git@main#egg=pylint -U``

**Comment by echoix** [comment]
Thanks @Pierre-Sassoulas! Indeed the git version could be used, but at some point to finish off my PR I should need a release at one point. 
Our codebase is stuck with a very old Pylint 2 version, and the most I was able to get it updated before breaking other jobs in the workflow was 2.12.2, but the Python version support is becoming limited. I worked against starting off from scratch with a complete new config, with Pylint 3.x.
What's hard with implementing it gradually is that contrary to flake8 and ruff, there's no way to have in a single place a list of files that ignores one or multiple rules each. That pattern is quite useful, as we can then fix gradually the issues (and we do!). For example, if an certain type of issue is in every `__init__.py`, we can specify it there until ready to fix, without disabling the rule for everywhere else, preventing introducing new problems. There's some plugin that seem to work in this idea, but I'm not that successful yet.

**Comment by Pierre-Sassoulas** [comment]
What I did in a project where I had this issue recently was to modify the python path with an init hook to add the source root to it ``init-hook='import sys; sys.path.append("/path/to/sourceroot")'``. (I did not actually check if this PR fix my issue, the problem with this hack is that it ruined my motivation to actually investigate the root cause in pylint... :/ ).

**Comment by echoix** [comment]
> What I did in a project where I had this issue recently was to modify the python path with an init hook to add the source root to it ``init-hook='import sys; sys.path.append("/path/to/sourceroot")'``. (I did not actually check if this PR fix my issue, the problem with this hack is that it ruined my motivation to actually investigate the root cause in pylint... :/ ).

Ours is quite sensitive to paths, as it uses some installed library and already have difficulty making normal imports work correctly... (we're working on it). The old way called Pylint 3 times, and had to be in different directories, with settings for each, not really easy to use for every contributor.

**Comment by o-moe** [comment]
@Pierre-Sassoulas Is it possible that this change introduce the false positive I am seeing? #10185

**Comment by Pierre-Sassoulas** [comment]
Thank you for the kind words, you're welcome ! It's possible, if you could `git bisect` to confirm that would be very helpful. (git clone the pylint repo, ``pip install -e``, ..)

**Comment by o-moe** [comment]
Sure, will report back with the result.

**Comment by o-moe** [comment]
@Pierre-Sassoulas git bisect seems to agree with my assumption. 
I started bisecting with the latest main HEAD (05e83c49d) as "bad" and v3.3.1 (76bce72) as "good" utilizing the example given in #10185 for verifying "good".

```shell
be530855265e6548ce1e5db54b2e3dd95448f45a is the first bad commit
commit be530855265e6548ce1e5db54b2e3dd95448f45a
Author: Julfried <51880314+Julfried@users.noreply.github.com>
Date:   Sun Oct 27 21:58:11 2024 +0100

    Fix source root not recognized (#10036)

 doc/whatsnew/fragments/10026.bugfix |  3 +++
 pylint/lint/expand_modules.py       |  2 +-
 tests/pyreverse/test_main.py        | 36 ++++++++++++++++++++++++++++++++++++
 3 files changed, 40 insertions(+), 1 deletion(-)
 create mode 100644 doc/whatsnew/fragments/10026.bugfix
```

Will also update this detail in the issue.

**Pull request merged**
