### PR TITLE
Add `--prefer-stubs=y` option

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description
Put the "prefer stubs" feature from pylint-dev/astroid#2375 under a feature flag.

Depends on https://github.com/pylint-dev/astroid/pull/2437.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
LGTM

**Review by Pierre-Sassoulas — APPROVED** [review]
Should we "hide" the astroid upgrades and create a fragment for each new things it brings (i.e. not in internal, like I did for 3.2.0) or announce them in internal (with functional changes too like you did here) ? Both work imo, and creating fragments for each new feature from astroid is more work.

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Need to upgrade the doc/example locally.

**Comment by jacobtylerwalls** [comment]
Ouch, re: windows failures. Here comes astroid 3.2.2....

[run on my fork showing that should take care of it](https://github.com/jacobtylerwalls/pylint/actions/runs/9113150847/job/25053947321?pr=34)

**Comment by jacobtylerwalls** [comment]
> Ouch, re: windows failures. Here comes astroid 3.2.2....

Luckily, it was just an issue with a nondeterminstic sort, fixed with a better test assertion.

**Review by Pierre-Sassoulas — APPROVED** [review]

**Pull request merged**
