### PR TITLE
Post pylint 3.0.3

### PR DESCRIPTION
**Pull request by jacobtylerwalls**

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Shouldn't this be a merge of the maintenance branch containing all the commit from maintenance/3.0.x ?

**Comment by jacobtylerwalls** [comment]
I rebased them out, was that wrong? I also had to manually delete the change log files.

**Comment by Pierre-Sassoulas** [comment]
We need to actually merge due to ``pre-commit autoupdate`` that do not understand what the latest version is otherwise. (Not much details in the doc but it's here: https://pylint.readthedocs.io/en/stable/development_guide/contributor_guide/release.html#releasing-a-patch-version). There's a lot of small conflicts and subtlety to handle each time, I usually freeze the main branch (do not merge something else in the meantime) and do a ``git diff origin/main`` during the mandatory 3 merge conflicts on versions before ``git merge --continue``. It permits to check that the diff to main make sense and have a single merge commit. (Especially since we'll need to merge later so fixup commit would be visible)

**Comment by jacobtylerwalls** [comment]
We should add an instruction to release.rst to go through and manually delete the changelog fragments. I just started attempting this from scratch and they still weren't picked up when merging maintenance into main.

**Comment by jacobtylerwalls** [comment]
(I'll do it the classic way in another MR so we can unblock things.)

**Pull request closed without merging**
