### PR TITLE
[release] Fix 3.2.4's release date following twine 5.1.0's issues

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |

## Description

See https://github.com/pylint-dev/pylint/actions/runs/9668507699/job/26672818926 and https://github.com/pypa/twine/issues/1125

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Planning to release 3.2.5 directly and not try to fix the 3.2.4 release to prevent mismatch between the existing tag and the version on pypi, but I'm open to suggestion.

**Review by jacobtylerwalls — APPROVED** [review]

**Comment by jacobtylerwalls** [comment]
Yeah, let's just go to 3.2.5 and mention in the release note there is no functional difference.

**Review by DanielNoord — COMMENTED** [review]
5.1.0 has been yanked, so I don't think this is necessary anymore :)

**Comment by Pierre-Sassoulas** [comment]
Yeap, re-running the release job worked. 👌 Thank you @DanielNoord

**Pull request merged**
