### PR TITLE
Rename checkers/async.py to async_checker.py to import from another module

### PR DESCRIPTION
**Pull request by bgb10**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description
image
image

Hi. Thank you for maintaining this great library :)
I wanted to make test code for `async` checkers, but **since name of async checker is `async.py`, AsyncChecker class in this file cannot be imported anywhere. ('async' is keyword!)**  Indeed, we imported this nowhere before (just registered checker to linter as below), but to write test code for AsyncChecker, file rename is must.

```python
def register(linter: PyLinter) -> None:
    linter.register_checker(AsyncChecker(linter))
```

After this PR merged, I'll want to make unit test code for AsyncChecker and adding some functionality.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the PR. Let's merge this but also if you want to add tests for the async checker functional tests already exists and are nicer to use imo. :)

**Review by Pierre-Sassoulas — APPROVED** [review]

**Review by DanielNoord — COMMENTED** [review]
This should probably have a `breaking` news fragment as it is breaking change.

**Comment by jacobtylerwalls** [comment]
Is it breaking if there was no way to import it by name before?

**Comment by DanielNoord** [comment]
Can't you use `importlib`? `pylint` itself has found a way to use this checker, so downstream users might have as well

**Comment by jacobtylerwalls** [comment]
Ah I see this is mentioned in the body: 

> Indeed, we imported this nowhere before

Agree a breaking fragment would
Be good.

**Comment by bgb10** [comment]
Thanks for review everybody 👍🏻 
yeah it is possible to use `importlib`, but I think it would be much better to prevent using filename as same as identifier.
Does this PR would be deferred until milestone 4.0.0?
I want to write test codes for `AsyncChecker`, so I don't want this PR to be blocker 😄

**Comment by jacobtylerwalls** [comment]
It's not a blocker, 4.0 is the current version under development.

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
(I approved because I thought like Jacob that it was impossible to import so it did not break anything). Considering Daniel's point, do you mind adding a changelog @bgb10 ?

**Comment by bgb10** [comment]
@Pierre-Sassoulas Added :)

**Review by Pierre-Sassoulas — APPROVED** [review]

**Comment by Pierre-Sassoulas** [comment]
Thank you,for noticing and fixing this ! (Autofix of 'noticing' to 'nothing'... mobile is dangerous, huhu)

**Pull request merged**
