### PR TITLE
Add home-assistant to primer and remove old external primer

### LINKED ISSUE #5359: Better primer tests (faster, less duplication, more diverse)
### Current problem

Right now the primer tests take more than double the time of the next slower tests. Also the CI configuration is duplicated between primer for stdlib and primer for external tests. The choice of repository to check is also arbitrary.

### Desired solution

- [x] #5425 > Burst the `primer-external` CI job into multiple jobs to cut down on CI run time
- [x] #5425 >  Remove the duplication in the GitHub action configuration and move `primer` to its own workflow file
- [ ] Clarify the criteria for choosing a repository and update the documentation
- [ ] Remove repositories that are redundant or less useful considering what we already have
- [x] Fixing dependency to a specific commit to be able to cache repository
- [x] Caching of repository for primers
- [x] Remove duplication in primer jobs by using a job template
- [x] #5425 >  Only run when something changes in `pylint` internals or `primer` testutils
- [x] Improve error message on crashes and fatal errors within the primer logs
- [ ] Check and see if CI workflow file can be shortened/improved

### Additional context

#5173

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :hammer: Refactoring   |

## Description
Restore `home-assistant` to the new primer, and finally remove the old (external) primer. The old (check for fatal only) primer still runs on the stdlib.

We were waiting for the 3.7 primer job to take less time before doing this, but we fixed that in #8608, and we're dropping 3.7 soon.

The commit string was too large for the cache action (512 chars ceiling), so I shortened the SHAs it uses.

Removed `keras`, as it wasn't linting successfully in this context, unfortunately.

[Successful run on my fork](https://github.com/jacobtylerwalls/pylint/actions/runs/4781412105/jobs/8499847553)

Closes #5359

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
Isn't keras failing in the "new" primer a valid reason to have it in the primer ? (If we only add projects that work from the get go we're selecting projects that are somewhat more compatible with pylint than the general projects pool)

**Comment by jacobtylerwalls** [comment]
> Isn't keras failing in the "new" primer a valid reason to have it in the primer ? (If we only add projects that work from the get go we're selecting projects that are somewhat more compatible with pylint than the general projects pool)

Keras works locally when fewer projects are involved. We're blowing out available memory on Github Actions, I assume. We probably have too many projects in the primer anyway. If we ever parallelized the primer job, we could consider adding it back.

**Review by Pierre-Sassoulas — APPROVED** [review]
👌

**Comment by Pierre-Sassoulas** [comment]
I was going to squash but it occurred to me that keeping the 4 commit separated in the history could be preferable, but there's a conflict so it's impossible to rebase. I'll let you choose what to do :)

**Comment by jacobtylerwalls** [comment]
We can squash it; we don't need a super-fine resolution on a git blame for this testing tool...

**Comment by DanielNoord** [comment]
I think this regressed? See https://github.com/pylint-dev/pylint/pull/8638, primer can't run anymore.

**Comment by jacobtylerwalls** [comment]
Taking a look

**Pull request merged**
