### PR TITLE
Extending redefined-outer-name check to cover the case of loop variables

### LINKED ISSUE #8646: Suggetion to improve redefined-outer-name or to introduce a new rule
### Current problem

The following code may not print what you expected on the last line:
```python
from collections import defaultdict
errors = [
    Exception("E101", "Boom!"),
    Exception("E101", "Bam!"),
    Exception("E102", "Shazam!"),
]
errors_per_arg0 = defaultdict(list)
for error in errors:
    errors_per_arg0[error.args[0]].append(error)
for arg0, errors in errors_per_arg0.items():
    print(arg0, "count:", len(errors))
print(errors)
```

The issue comess from the `for` loop, where the `errors` loop variable shadows the previously defined list.

The problem is that, on the last line, `errors` is now a 1-item list!

As far as I know, Pylint currently does not have any rule that detects this.
`redefined-outer-name` for example, does not get triggered.

### Desired solution

First, I'd like to know what Pylint maintainers think to be the best approach:
* improve the existing `redefined-outer-name` to cover this
* introduce a new rule to detect this case

### Additional context

There are some edge cases to consider when such case happens, where the definition of loop variable "erases" a variable in the current scope:
* if this variable is not used after the loop, should an error be raised?
* if this variable is re-assigned after the loop, before being read, should an error be raised?

### PR DESCRIPTION
**Pull request by Lucas-C**
- [x] Document your change, if it is a non-trivial one.
- [x] Keep the change small, separate the consensual changes from the opinionated one.

## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description
Extend the rule `redefined-outer-name` to cover the case of loop variables shadowing previously defined variables.

Closes #8646

### CODE REVIEW

**Comment by Lucas-C** [comment]
There is a case that I have trouble to handle / ignore :

```python
#--- Notable cases where redefined-outer-name should NOT be raised:

# When the loop variable is re-assigned:
for i in enumerate(errors):
    i += 1
```

Would you have suggestions on how to NOT raise `redefined-outer-name` for this situation?

**Comment by Lucas-C** [comment]
> There is a case that I have trouble to handle / ignore :
> 
> ```python
> #--- Notable cases where redefined-outer-name should NOT be raised:
> 
> # When a similarly named loop variable is assigned in another loop:
> for n in range(10):
>     n += 1
> for n in range(10):
>     n += 1
> ```
> 
> Would you have suggestions on how to NOT raise `redefined-outer-name` for this situation?

I think I found the solution!

**Comment by Pierre-Sassoulas** [comment]
> Now this is the case I'm wondering about:
> for value in range(10):
>    pass
>value = 42
> The current version of the checker will raise a redefined-outer-name for this code snippet.

It seems like it's more of a redefined-inner-name (or preredefined-outer-name) in this case 😄 Potentially problematic but does not feel like the same issue.

**Comment by Lucas-C** [comment]
I think this PR is ready for review! 😊

**Comment by Lucas-C** [comment]
The `mypy` check from `pre-commit` signals a problem that I do not understand:
```
pylint/checkers/variables.py:3395: error: Returning Any from function declared to return "bool"  [no-any-return]
```

Related code:
```python
    for node in assign.node_ancestors():
        if node is for_node.parent:
            return assign.lineno > for_node.lineno
    return False
```

**Comment by Pierre-Sassoulas** [comment]
astroid is not officially typed so ``assign.lineno`` and ``for_node.lineno`` are considered an ``Any`` (not an int like they should). That being said, it feels like a mypy bug because ``>`` returns a boolean.

**Comment by Pierre-Sassoulas** [comment]
https://github.com/python/mypy/issues/5697#issuecomment-425738430

**Comment by Pierre-Sassoulas** [comment]
It look like I already linked to this mypy issue , one year and one day ago. Guess I never learn.

**Comment by Lucas-C** [comment]
> [python/mypy#5697 (comment)](https://github.com/python/mypy/issues/5697#issuecomment-425738430)

Interesting.

What do you recommend in that case? Adding `# type: ignore` on this line?

**Comment by Pierre-Sassoulas** [comment]
> # type: ignore

Yeah, ``# type: ignore[no-any-return]``, then we're going to remove it once astroid is typed officially, a lot of effort is made in this direction.

**Comment by Lucas-C** [comment]
> Yeah, `# type: ignore[no-any-return]`, then we're going to remove it once astroid is typed officially, a lot of effort is made in this direction.

OK, done

**Comment by Lucas-C** [comment]
For reference, with this change Pylint now raises several extra issues on its own code:
```
************* Module pylint.pyreverse.mermaidjs_printer
pylint/pyreverse/mermaidjs_printer.py:62:8: W0621: Redefining name 'line' from outer scope (line 54) (redefined-outer-name)
************* Module pylint.checkers.typecheck
pylint/checkers/typecheck.py:1166:12: W0621: Redefining name 'name' from outer scope (line 1097) (redefined-outer-name)
pylint/checkers/typecheck.py:1599:12: W0621: Redefining name 'i' from outer scope (line 1552) (redefined-outer-name)
pylint/checkers/typecheck.py:1620:8: W0621: Redefining name 'name' from outer scope (line 1506) (redefined-outer-name)
************* Module pylint.checkers.exceptions
pylint/checkers/exceptions.py:52:4: W0621: Redefining name 'inferred' from outer scope (line 48) (redefined-outer-name)
************* Module pylint.testutils.functional.find_functional_tests
pylint/testutils/functional/find_functional_tests.py:100:12: W0621: Redefining name 'error_msg' from outer scope (line 83) (redefined-outer-name)
pylint/testutils/functional/find_functional_tests.py:128:8: W0621: Redefining name 'possible_dir' from outer scope (line 114) (redefined-outer-name)
************* Module pylint.checkers.format
pylint/checkers/format.py:524:8: W0621: Redefining name 'line' from outer scope (line 511) (redefined-outer-name)
************* Module pylint.pyreverse.inspector
pylint/pyreverse/inspector.py:367:12: W0621: Redefining name 'fpath' from outer scope (line 353) (redefined-outer-name)
************* Module pylint.checkers.classes.class_checker
pylint/checkers/classes/class_checker.py:90:4: W0621: Redefining name 'arg' from outer scope (line 80) (redefined-outer-name)
pylint/checkers/classes/class_checker.py:1828:8: W0621: Redefining name 'callee' from outer scope (line 1825) (redefined-outer-name)
pylint/checkers/classes/class_checker.py:2165:8: W0621: Redefining name 'method' from outer scope (line 2155) (redefined-outer-name)
************* Module pylint.checkers.strings
pylint/checkers/strings.py:316:20: W0621: Redefining name 'key' from outer scope (line 302) (redefined-outer-name)
pylint/checkers/strings.py:321:16: W0621: Redefining name 'key' from outer scope (line 302) (redefined-outer-name)
pylint/checkers/strings.py:326:16: W0621: Redefining name 'key' from outer scope (line 302) (redefined-outer-name)
pylint/checkers/strings.py:386:16: W0621: Redefining name 'format_type' from outer scope (line 329) (redefined-outer-name)
************* Module pylint.checkers.imports
pylint/checkers/imports.py:99:4: W0621: Redefining name 'first' from outer scope (line 95) (redefined-outer-name)
************* Module unittest_multi_naming_style
tests/checkers/base/unittest_multi_naming_style.py:49:12: W0621: Redefining name 'cls' from outer scope (line 48) (redefined-outer-name)
tests/checkers/base/unittest_multi_naming_style.py:98:12: W0621: Redefining name 'cls' from outer scope (line 97) (redefined-outer-name)
tests/checkers/base/unittest_multi_naming_style.py:136:12: W0621: Redefining name 'func' from outer scope (line 135) (redefined-outer-name)
tests/checkers/base/unittest_multi_naming_style.py:173:12: W0621: Redefining name 'func' from outer scope (line 172) (redefined-outer-name)
************* Module pylint.checkers.similar
pylint/checkers/similar.py:439:8: W0621: Redefining name 'num' from outer scope (line 413) (redefined-outer-name)
pylint/checkers/similar.py:464:12: W0621: Redefining name 'line_set' from outer scope (line 463) (redefined-outer-name)
pylint/checkers/similar.py:464:12: W0621: Redefining name 'start_line' from outer scope (line 463) (redefined-outer-name)
pylint/checkers/similar.py:464:12: W0621: Redefining name 'end_line' from outer scope (line 463) (redefined-outer-name)
pylint/checkers/similar.py:871:12: W0621: Redefining name 'lineset' from outer scope (line 870) (redefined-outer-name)
pylint/checkers/similar.py:871:12: W0621: Redefining name 'start_line' from outer scope (line 870) (redefined-outer-name)
pylint/checkers/similar.py:871:12: W0621: Redefining name 'end_line' from outer scope (line 870) (redefined-outer-name)
************* Module pylint.pyreverse.plantuml_printer
pylint/pyreverse/plantuml_printer.py:78:8: W0621: Redefining name 'line' from outer scope (line 68) (redefined-outer-name)
************* Module pylint.checkers.refactoring.refactoring_checker
pylint/checkers/refactoring/refactoring_checker.py:1576:8: W0621: Redefining name 'value' from outer scope (line 1566) (redefined-outer-name)
```

I can do the job of fixing all those places,
but could I have some approval of the overral relevance of this PR?


Basically, I don't want to spend a few hours fixing Pylint to then discover that this PR is not welcome,
for example because it triggers to many new warnings 😅

**Comment by Pierre-Sassoulas** [comment]
> Basically, I don't want to spend a few more hours on this PR to then discover that it is not really welcome,
for example because it triggers to many new warnings

Yes, it seems like a risk. I think we need the pylint check to be green in order to see the primer result, could you add a disable for redefined-outer-name in our pylintrc so the pylint test is green and we can see the result of the primer on more packages please ?

**Comment by Lucas-C** [comment]
> could you add a disable for redefined-outer-name in our pylintrc so the pylint test is green and we can see the result of the primer on more packages please ?

Sure, done

**Comment by Lucas-C** [comment]
Hi
Just a suggestion: as this PR is waiting for feedback, maybe it should be tagged `Needs decision` or `Needs review`?

**Comment by Pierre-Sassoulas** [comment]
Hey @Lucas-C could you rebase on main ? There was an issue in the primer that was fixed in #8676

**Comment by Lucas-C** [comment]
> Hey @Lucas-C could you rebase on main ? There was an issue in the primer that was fixed in #8676

Sure, done

**Review by jacobtylerwalls — CHANGES_REQUESTED** [review]
Thanks for your patience with the review. I pushed some temporary changes that should get the primer to finish. We're generating so many messages (in general, but also with this PR in particular) that the job could never finish. Obviously this is a symptom of needing to parallelize our testing tool, but it's also a symptom that a lot of messages will be emitted.

I'll circle back when the primer tool posts its comment. In the meantime, found one bug ⬇️

**Comment by Pierre-Sassoulas** [comment]
If there's so much messages that it's crashing the primer we probably can't just extend an existing message, we'd need a new one (if we even want to add the message, because if a construct is used extensively in popular project it's probably not a code smell ?).  There's a lot of violations in pylint's as we saw previously.

**Comment by jacobtylerwalls** [comment]
I can just stop fiddling with the primer and run it manually. Here are the five results from linting astroid:

```
% pylint astroid --disable=all --enable=redefined-outer-name
************* Module astroid.builder
astroid/builder.py:342:8: W0621: Redefining name 'child' from outer scope (line 333) (redefined-outer-name)
************* Module astroid.inference
astroid/inference.py:542:8: W0621: Redefining name 'value' from outer scope (line 541) (redefined-outer-name)
************* Module astroid.nodes.node_classes
astroid/nodes/node_classes.py:107:4: W0621: Redefining name 'inferred' from outer scope (line 102) (redefined-outer-name)
************* Module astroid.brain.brain_gi
astroid/brain/brain_gi.py:140:4: W0621: Redefining name 'obj' from outer scope (line 75) (redefined-outer-name)
************* Module astroid.brain.brain_multiprocessing
astroid/brain/brain_multiprocessing.py:37:4: W0621: Redefining name 'node' from outer scope (line 24) (redefined-outer-name)
```

**1**
I'd consider a false positive, since the two uses are in exclusive branches. Try:
```diff
diff --git a/pylint/checkers/variables.py b/pylint/checkers/variables.py
index 55fce29d3..ca73a5182 100644
--- a/pylint/checkers/variables.py
+++ b/pylint/checkers/variables.py
@@ -1306,6 +1306,8 @@ class VariablesChecker(BaseChecker):
             for ref in node.scope().locals.get(target.name, []):
                 if ref == target:
                     continue
+                if astroid.nodes.node_classes.are_exclusive(ref, target):  # with a better import...
+                    continue
                 if isinstance(ref.parent, nodes.Arguments):
                     continue  # ignoring case covered by redefined-argument-from-local
                 if self._dummy_rgx and self._dummy_rgx.match(target.name):
```

**2-5**
I'd consider false positive-ish: they all follow a return or a yield. I'd suggest checking for return/yield anywhere between `ref` and `target` and short-circuit.

It's possible that would get the number of new messages down to an acceptable level, but I can't guarantee it until seeing the results (sorry!)

**Comment by jacobtylerwalls** [comment]
Hi @Lucas-C :wave:
Do you think you will have time to reengage here?

**Comment by jacobtylerwalls** [comment]
Feel free to reopen if you return to this 👍

**Pull request closed without merging**
