### PR TITLE
Upgrade astroid to 2.15.3

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :sparkles: New feature |

## Description

Upgrade astroid for next patch release.

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
Are you able to reproduce the failure?

**Comment by Pierre-Sassoulas** [comment]
I need to install an older python interpreter, I'm going to check that tomorrow.

**Comment by Pierre-Sassoulas** [comment]
I won't be able to reproduce this or release pylint 2.17.3 before at least this week-end (traveling for work). astroid 2.15.3 is live so we might have a regression on our hand in pylint 2.17.2 (#4439)

**Comment by Pierre-Sassoulas** [comment]
Nice catch @cdce8p, I missed that attr is not in pytest anymore and I reviewed that changelog entry in pytest 🤦

**Review by cdce8p — APPROVED** [review]

**Pull request merged**
