### PR TITLE
Fix max-positional-arguments comments in example config files

### PR DESCRIPTION
**Pull request by correctmost**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :scroll: Docs          |

## Description
The comment for `min-public-methods` got accidentally reused.

### CODE REVIEW

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Nice catch ! This is generated using this:

https://github.com/pylint-dev/pylint/blob/02616372282fd84862636d58071e6f3c62b53559/tbump.toml#L40-L46

Something need to change in the code directly, and the toml would be modified too. (No need to use tbump, you can launch the command directly)

**Review by jacobtylerwalls — CHANGES_REQUESTED** [review]
sorry, I see from Pierre's comment that this wasn't generated using the command.

**Comment by jacobtylerwalls** [comment]
We will also want the toml file updated.

**Review by jacobtylerwalls — APPROVED** [review]

**Comment by jacobtylerwalls** [comment]
Thanks!

**Comment by Pierre-Sassoulas** [comment]
I was wondering why nothing changed in the code. Then I realized that it was a missing generation following another earlier fix. Would have been fixed for 3.3.0 release but we could add it to pre-commit or the doc pipeline to avoid this.

**Pull request merged**
