### PR TITLE
Also check the typealias naming style for TypeAlias variables defined in functions.

### LINKED ISSUE #8536: TypeAlias defined inside functions doesn't respect the typealias naming style.
### Bug description

Example code:

```python
# pylint: disable=missing-docstring
from typing import TypeAlias

GoodTopLevelName: TypeAlias = int
bad_top_level_name: TypeAlias = int


def my_func():
    GoodLocalName: TypeAlias = int
    bad_local_name : TypeAlias = int
    del GoodLocalName, bad_local_name
```

### Configuration

_No response_

### Command used

```shell
pylint t.py
```

### Pylint output

```shell
t.py:5:0: C0103: Type alias name "bad_top_level_name" doesn't conform to predefined naming style (invalid-name)
```

### Expected behavior

It should also raise `invalid-name` for the `bad_local_name ` variable

### Pylint version

```shell
pylint 2.17.2
astroid 2.15.2
Python 3.11.2 (main, Mar  3 2023, 16:02:46) [GCC 12.2.0]
```

### OS / Environment

_No response_

### Additional dependencies

I having a PR coming.

### PR DESCRIPTION
**Pull request by yilei**
## Type of Changes

|     | Type                   |
| --- | ---------------------- |
| ✓   | :bug: Bug fix          |
|    | :sparkles: New feature |
|    | :hammer: Refactoring   |
|    | :scroll: Docs          |

## Description

Closes #8536

### CODE REVIEW

**Comment by yilei** [comment]
Btw, `tests/test_check_parallel.py` seems to be failing when I run tests locally at HEAD:

```
platform darwin -- Python 3.11.1, pytest-7.2.2, pluggy-1.0.0

...

=========================================================================================================== FAILURES ============================================================================================================
________________________________________________________________________ TestCheckParallelFramework.test_linter_with_unpickleable_plugins_is_pickleable _________________________________________________________________________

self = <test_check_parallel.TestCheckParallelFramework object at 0x10a4eb710>

    def test_linter_with_unpickleable_plugins_is_pickleable(self) -> None:
        """The linter needs to be pickle-able in order to be passed between workers"""
        linter = PyLinter(reporter=Reporter())
        # We load an extension that we know is not pickle-safe
        linter.load_plugin_modules(["pylint.extensions.overlapping_exceptions"])
        try:
            dill.dumps(linter)
>           raise AssertionError(
                "Plugins loaded were pickle-safe! This test needs altering"
            )
E           AssertionError: Plugins loaded were pickle-safe! This test needs altering

tests/test_check_parallel.py:252: AssertionError
```

**Review by Pierre-Sassoulas — APPROVED** [review]
Neat fix ! @DanielNoord do you have an opinion about the pickle test failing ?

**Comment by DanielNoord** [comment]
Can we reproduce? If not I'd say just merge this

**Review by Pierre-Sassoulas — CHANGES_REQUESTED** [review]
Reading the primer it seems some variable that are only typed are confused for a TypeAlias. For example in sentry: ``        resolved_orderby: Union[str, SelectType, None]``

**Comment by yilei** [comment]
@Pierre-Sassoulas Is "primer" the Primer actions run on this PR? Could you please point to me where the relevant outputs are? I checked those jobs but can only find generic logs without info like sentry / `resolved_orderby: Union[str, SelectType, None]`. Thanks!

**Comment by yilei** [comment]
@Pierre-Sassoulas Ah sorry never mind, just found out it's in a separate comment right after I posted my question. Taking a look now.

**Comment by yilei** [comment]
Rebased, the local variable declaration issue should have been fixed by #8541.

**Review by DanielNoord — APPROVED** [review]
@Pierre-Sassoulas Do you want a review as well?

**Review by Pierre-Sassoulas — APPROVED** [review]
Neat !

**Pull request merged**
